#! /bin/sh 

case "$1" in 
  start) 
    echo "Starting module abc" 
    ../etc/init.d/module_load faulty
    ../etc/init.d/scull_load 
    modprobe hello.o
    ;; 
  stop) 
    echo "Stopping module" 
    ../etc/init.d/scull_unload
    ../etc/init.d/module_unload faulty
    rmmod hello.o
    ;; 
  *) 
    echo "Usage: $0 {start|stop}" 
  exit 1 
esac 
 
exit 0 
